version: 0.2 # build spec version

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-2"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u "$DOCKER_HUB_ID" --password-stdin
      # - echo Pulling Docker Images for cache...
      # - docker-compose pull --ignore-pull-failures -q
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t hjun/docker-frontend ./frontend
      - docker build -t hjun/docker-backend ./backend
      - docker build -t hjun/docker-ngnix ./ngnix
  post_build:
    commands:
      - docker push hjun/docker-frontend
      - docker push hjun/docker-backend
      - docker push hjun/docker-ngnix

artifacts:
  files:
    - "./**/*"
