version: "2.4"
services:
  frontend:
    image: hjun121345/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: hjun121345/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: hjun121345/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    # environment:
    #   - name=value

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Hjun
  #     MYSQL_DATABASE: myapp
  #   platform: linux/x86_64
